# Generated by Django 3.1 on 2020-09-08 14:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_channel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='date',
            field=models.DateField(default=datetime.date(1111, 11, 11)),
        ),
    ]
