# Generated by Django 3.1 on 2020-10-23 15:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_channel_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='contact',
            field=models.IntegerField(default='', max_length=11),
        ),
        migrations.AlterField(
            model_name='channel',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
