# Generated by Django 3.1 on 2020-10-23 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20201023_2119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='contact',
        ),
    ]
