# Generated by Django 3.1 on 2020-11-06 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_remove_channel_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='desc',
            field=models.CharField(max_length=200),
        ),
    ]
