# Generated by Django 3.1 on 2020-11-06 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20201106_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='email',
            field=models.EmailField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='channel',
            name='phone',
            field=models.CharField(max_length=13, null=True),
        ),
    ]
