# Generated by Django 3.1 on 2020-11-25 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_channel_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='image',
            field=models.ImageField(default='defaultuser.jpg', upload_to='user/images'),
        ),
    ]
